### ISSUE TITLE
Support ARM architectures

### ISSUE THREAD

**Issue by mycaule** [cloud-helpers/cloud-python-images#2]
Hello,

I am trying to use EMR with Graviton, expecting quick wins on both performance and costs grounds as told in [this article](https://aws.amazon.com/blogs/big-data/amazon-emr-now-provides-up-to-30-lower-cost-and-up-to-15-improved-performance-for-spark-workloads-on-graviton2-based-instances/).

I tried to run my workload on EMR + Docker on EC2 **m6g** instances while building my Dockerfile for the linux/arm64 target platform, using base image `infrahelpers/cloud-python:pyspark-emr6-light`

Yet, my job doesn't start, I suspect because of these two lines that aren't ARM compatible.

https://github.com/cloud-helpers/cloud-python-images/blob/dafcf17df2196076cbf5f8591056901749a79ad4/pyspark-emr-6-coretto-8-light/Dockerfile#L53

(`https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip` would be the correct file for ARM architecture)

https://github.com/cloud-helpers/cloud-python-images/blob/dafcf17df2196076cbf5f8591056901749a79ad4/pyspark-emr-6-coretto-8-light/Dockerfile#L62

(`https://github.com/Versent/saml2aws/releases/download/v2.36.0/saml2aws_2.36.0_linux_arm64.tar.gz` would be the correct file)

According to https://hub.docker.com/_/amazoncorretto, amazoncorretto supports `arm64` though.

Do you have an elegant way to provide a multiplatform image?

## References

- https://stormacq.com/podcasts/episode_097/index.html
- https://youtu.be/TdQeACV75ao?t=3445
- https://www.docker.com/blog/speed-up-building-with-docker-buildx-and-graviton2-ec2/

**Comment by da115115** [comment]
Support integrated thanks to your pull request (https://github.com/cloud-helpers/cloud-python-images/pull/3)!
